[package]
name = "screen_stream_x"
version = "0.1.0"
authors = ["Stefano Roy Bisignano <stefano2001roy@gmail.com>"]
edition = "2021"
# Dipendenze del progetto
[dependencies]
egui = "0.28.0"
eframe = "0.28.1"
winit = "0.30.4"